server:
  port: ${PORT:8081}
  servlet:
    context-path: /upsign

spring:
  application:
    name: upsignapi
    version: v0.0.1BETA
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always
  jpa:
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM:org.hibernate.dialect.PostgreSQL92Dialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

#AWS properties
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:awsaccesskey}
      secretKey: ${AWS_SECRET_ACCESS_KEY:secretkey}

app:
  jwtSecret: JWTSecretNoOneCanCrack
  jwtExpirationInMs: 3600000
  awsServices:
    bucketName: ${S3_BUCKET_NAME:s3bucketname}
