server:
  port: ${PORT:8081}
  servlet:
    context-path: /antlogic

spring:
  application:
    name: ant
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ec2-174-129-33-120.compute-1.amazonaws.com:5432/d4sp6nouhfrhik}
    username: ${SPRING_DATASOURCE_USERNAME:tckxrwltkbijbv}
    password: ${SPRING_DATASOURCE_PASSWORD:d3f8b3998f686940d4461077593bc44dbd18d42449eb2e757050c821e2f91477}
    initialization-mode: always
  jpa:
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM:org.hibernate.dialect.PostgreSQL92Dialect}
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

#AWS properties
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:awsaccesskey}
      secretKey: ${AWS_SECRET_ACCESS_KEY:secretkey}

app:
  jwtSecret: JWTSecretNoOneCanCrack
  jwtExpirationInMs: 3600000
  awsServices:
    bucketName: ${S3_BUCKET_NAME:s3bucketname}